server:
  port: 8080

spring:
  application:
    name: hostel-management-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/hostel_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "pass"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:hostel.management.notifications@gmail.com}
    password: ${EMAIL_PASS:dummy-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  jwt:
    secret: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
    expiration-ms: 86400000 # 24 hours
  notifications:
    enabled: false # Set true to send real emails

logging:
  level:
    root: INFO
    com.hostel: DEBUG
